from turtle import *
import turtle as tur

turt = tur.Turtle()
tur.title("Superman")
turt.turtlesize(5,1,1)
turt.pensize(3)

ws=tur.Screen().bgcolor('navy')

def codepeak(x, y):
    penup()
    goto(x, y)
    pendown()


def curve(value):
    for i in range(value):
        turt.right(1)
        turt.forward(1)

turt.penup()
turt.setposition(0,43)
turt.pendown()
turt.begin_fill()
turt.pencolor('black')
turt.fillcolor('maroon')
turt.pensize(3)
turt.forward(81.5)
turt.right(49.4)
turt.forward(58)
turt.right(81.42)
turt.forward(182)
turt.right(98.36)
turt.forward(182)
turt.right(81.42)
turt.forward(58)
turt.right(49.4)
turt.forward(81.5)
turt.end_fill()
turt.penup()

turt.setposition(38,32)
turt.pendown()
turt.begin_fill()
turt.fillcolor('gold')
turt.forward(13)
turt.right(120)
turt.forward(13)
turt.right(120)
turt.forward(13)
turt.end_fill()
turt.penup()

turt.setposition(81.5,25)
turt.pendown()
turt.begin_fill()
turt.right(210)
turt.forward(25)
turt.right(90)
turt.forward(38)
turt.right(45)
turt.circle(82,90)
turt.left(90)
turt.circle(82,60)
curve(61)
turt.left(90)
turt.forward(57)
turt.left(90)
turt.forward(32)
turt.end_fill()
turt.penup()
turt.home()

turt.setposition(-69,-38)
turt.pendown()
turt.begin_fill()
curve(20)
turt.forward(33)
turt.left(10)
turt.circle(82,20)
curve(30)
turt.forward(10)
turt.right(110)
curve(40)
turt.right(10)
turt.circle(50,10)
curve(45)
turt.right(5)
turt.forward(45)
turt.end_fill()
turt.penup()
turt.home()

turt.setposition(20,-100)
turt.pendown()
turt.begin_fill()
turt.right(135)
turt.forward(27)
turt.right(90)
turt.forward(27)
turt.right(135)
turt.forward(38.18)
turt.end_fill()
turt.penup()
turt.home()

turt.setposition(-57,32)
turt.pendown()
turt.begin_fill()
turt.right(180)
turt.forward(18)
turt.left(45)
turt.forward(44)
turt.left(80)
turt.forward(15)
turt.left(130)
curve(40)
turt.forward(20)
turt.end_fill()

codepeak(80, -200)
write('CodePeak 2022', font=("Bradley Hand ITC", 30, "bold"))

turt.hideturtle()
tur.exitonclick()